In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'1.1.0'

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.dtype

dtype('int32')

In [7]:
type(arr)

numpy.ndarray

In [8]:
x =torch.from_numpy(arr)

In [9]:
type(x)

torch.Tensor

In [10]:
y = torch.as_tensor(arr)

In [11]:
type(y)

torch.Tensor

In [12]:
arr2d = np.arange(0.0, 12.0)

In [13]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [14]:
arr2d = arr2d.reshape(4,3)

In [15]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [16]:
x2 = torch.from_numpy(arr2d)

In [17]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [18]:
arr

array([1, 2, 3, 4, 5])

In [19]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [20]:
arr[0] = 99

In [21]:
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [22]:
my_arr = np.arange(0,10)

In [23]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
my_tensor = torch.tensor(my_arr)

In [25]:
my_other_tensor = torch.from_numpy(my_arr)

In [26]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [27]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [28]:
my_arr[0] = 9999

In [29]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [30]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       dtype=torch.int32)

In [31]:
new_arr = np.array([1,2,3])

In [32]:
new_arr.dtype

dtype('int32')

In [33]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [34]:
torch.Tensor(new_arr)

tensor([1., 2., 3.])

In [35]:
torch.empty(4,2)

tensor([[5.4654e+22, 1.0081e-08],
        [1.0991e-05, 3.4305e-06],
        [5.1475e-11, 7.1450e+31],
        [1.6534e+19, 3.0854e+32]])

In [36]:
torch.zeros(4,3,dtype = torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [37]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [38]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [39]:
torch.linspace(0,1, 12).reshape(3,4)

tensor([[0.0000, 0.0909, 0.1818, 0.2727],
        [0.3636, 0.4545, 0.5455, 0.6364],
        [0.7273, 0.8182, 0.9091, 1.0000]])

In [40]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [41]:
my_tensor = torch.tensor([1,2,3])

In [42]:
my_tensor.dtype

torch.int64

In [43]:
my_tensor = my_tensor.type(torch.int32)

In [44]:
my_tensor.dtype

torch.int32

In [45]:
torch.rand(4,3)

tensor([[0.6758, 0.9228, 0.2776],
        [0.9195, 0.8577, 0.3535],
        [0.3984, 0.3381, 0.4792],
        [0.2953, 0.5467, 0.3758]])

In [46]:
torch.randn(4,3)

tensor([[ 2.1955,  0.0044,  0.5906],
        [-0.2043, -0.4460,  0.5876],
        [ 0.3794, -0.8506,  0.0164],
        [-0.4807,  0.3705, -0.2131]])

In [47]:
torch.randint(low=0, high = 257, size = (5,5))

tensor([[ 89, 165, 130,  84, 219],
        [204,  68, 161,  75, 148],
        [ 71, 238,  55,  73, 179],
        [ 68, 169, 204,  55,  25],
        [183, 148,   1, 232, 227]])

In [48]:
x = torch.zeros(2,5)

In [49]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [50]:
x.shape

torch.Size([2, 5])

In [51]:
torch.rand_like(x)

tensor([[0.9570, 0.6010, 0.4644, 0.9444, 0.9365],
        [0.4401, 0.1623, 0.7925, 0.3318, 0.5593]])

In [52]:
torch.randn_like(x)

tensor([[ 2.2915, -1.0135, -1.6661,  1.0106, -0.8939],
        [ 0.3525,  0.5202,  0.1676,  1.8738, -0.5826]])

In [53]:
torch.randint_like(x, low = 0, high = 11)

tensor([[0., 4., 5., 0., 4.],
        [4., 2., 4., 3., 5.]])

In [54]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [55]:
import numpy as np

In [56]:
x = torch.arange(6).reshape(3,2)

In [57]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [58]:
type(x[1,1])

torch.Tensor

In [59]:
x[:,1]

tensor([1, 3, 5])

In [60]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [61]:
x = torch.arange(10)

In [62]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [64]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [66]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [67]:
a = torch.tensor([1.,2.,3.])

In [68]:
b = torch.tensor([4.,5.,6.,])

In [69]:
a.dtype

torch.float32

In [70]:
a + b 

tensor([5., 7., 9.])

In [71]:
torch.add(a,b)

tensor([5., 7., 9.])

In [72]:
a.mul(b)

tensor([ 4., 10., 18.])

In [73]:
a

tensor([1., 2., 3.])

In [74]:
a*b

tensor([ 4., 10., 18.])

In [75]:
a.mul(b)

tensor([ 4., 10., 18.])

In [76]:
a.dot(b)

tensor(32.)

In [77]:
a = torch.tensor([[0,2,4], [1,3,5]])

In [79]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [80]:
a.shape

torch.Size([2, 3])

In [81]:
b.shape

torch.Size([3, 2])

In [85]:
torch.mm(b,a)

tensor([[ 7, 33, 59],
        [ 9, 43, 77],
        [11, 53, 95]])

In [84]:
a@b

tensor([[56, 62],
        [80, 89]])

In [87]:
x = torch.tensor([2.,3.,4.,5.])

In [88]:
x

tensor([2., 3., 4., 5.])

In [ ]:
x.