In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [5]:
arr = np.array(mylist)

In [6]:
arr

array([1, 2, 3])

In [8]:
mylist = [[1,2,3], [4,5,6], [7,8,9]]

In [13]:
mymatrix =  np.array(mylist)

In [16]:
mymatrix.shape

(3, 3)

In [17]:
mynewmatix = np.array(mylist)

In [22]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
type(0.0)

float

In [28]:
np.zeros((4,10))


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [33]:
np.ones(4)*100

array([100., 100., 100., 100.])

In [35]:
[1,1,1,1] * 100

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [41]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [43]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.random.rand(4)

array([0.88331054, 0.9959863 , 0.54290581, 0.82425162])

In [50]:
np.random.randn(10)

array([-1.25539857,  0.25398852, -0.51696849,  0.30934374, -1.60192115,
       -0.3091166 ,  1.61322751,  2.59410749,  1.42514663, -0.51558336])

In [ ]:
np.random.normal

In [53]:
np.random.randint(1,10,3)

array([7, 8, 1])

In [59]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [60]:
np.random.rand(4)

array([0.58120733, 0.14267862, 0.94591918, 0.33999059])

In [61]:
arr = np.arange(25)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [63]:
ranarr = np.random.randint(0,50,10)

In [64]:
ranarr

array([10, 21, 27, 28, 48,  4,  1, 42, 41, 20])

In [69]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
ranarr.max()

48

In [72]:
ranarr.min()

1

In [73]:
ranarr.argmax()

4

In [74]:
ranarr.argmin()

6

In [75]:
ranarr.dtype

dtype('int32')

In [76]:
arr = np.arange(0,11)

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr[8]

8

In [79]:
arr[1:5]

array([1, 2, 3, 4])

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [83]:
new_arr = arr /2

In [84]:
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [87]:
slice_of_arr = arr[0:6]

In [88]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [90]:
slice_of_arr[:] = 99

In [96]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [97]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [93]:
arr_copy = arr.copy()

In [95]:
arr_copy[:] = 10000

In [98]:
arr_copy

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000])

In [99]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [100]:
# INDEXING on 2d array

In [102]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [103]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [104]:
arr_2d.shape

(3, 3)

In [111]:
arr_2d[2][2]

45

In [114]:
arr_2d[0:2, 1]

array([10, 25])

In [115]:
arr = np.arange(1,11)

In [116]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [123]:
bool_arr = arr > 4

In [124]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [125]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [126]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [128]:
arr[arr <= 6]

array([1, 2, 3, 4, 5, 6])

In [129]:
arr = np.arange(0,10)

In [130]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [132]:
arr /100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [133]:
arr **2 

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [135]:
(arr + 2)/100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [136]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [137]:
1/arr

C:\Users\Seedevice\anaconda3\envs\pytorchenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [138]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [139]:
np.log(arr)

C:\Users\Seedevice\anaconda3\envs\pytorchenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [140]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [142]:
arr.sum()

45

In [143]:
arr.mean()

4.5

In [144]:
arr.max()

9

In [145]:
arr_2d = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])

In [146]:
arr_2d.shape

(3, 4)

In [147]:
arr_2d.sum()

78

In [150]:
arr_2d.sum(axis = 1)

array([10, 26, 42])

In [151]:
arr_2d.sum(axis = 0)

array([15, 18, 21, 24])